#!/bin/bash

mkdir -p "$USER_DIR"/.drm/bin
cd $USER_DIR/.drm/bin

go get github.com/dbdevs/drm
go get github.com/codegangsta/cli
go get github.com/barkerd427/dockerclient

if [ "$1" == "mac" ]; then
  export GOOS=darwin
  export GOARCH=amd64
elif [ "$1" == "linux" ]; then
  export GOOS=linux
  export GOARCH=amd64
fi

go build -v -x /go/src/github.com/dbdevs/drm/drm.go

cp /function.sh "$USER_DIR"/.drm/

env_files=( "${USER_DIR}/.bashrc" "${USER_DIR}/.bash_profile" "${USER_DIR}/.zshrc" )
for file in "${env_files[@]}"
do
	eval "file=$file" # expand the path correctly

	if [[ ! -f $file ]]
	then
		touch $file
	fi

	if grep -q "source ~/.drm/function.sh" $file
	then
		continue
	fi

	echo "Adding env entries to: $file"
	cat - >> $file <<-EOF
		# Generated by: DRM
		source ~/.drm/function.sh
	EOF

	if (( $? ))
	then
		echo "Error updating file [$file]"
		exit 1
	fi
done

if [ "$1" != "mac" ] || [ "$1" != "linux" ]; then
  exec "$@"
fi