#!/usr/bin/env bash

docker build -f Dockerfile -t drm_mac .
mkdir -p ~/.drm/bin
docker run --rm -v ~/.drm/bin:/.drm/bin -w /.drm/bin drm_mac
cp function.sh ~/.drm
chmod +x ~/.drm/bin/drm

env_files=( "~/.bashrc" "~/.bash_profile" "~/.zshrc" )
for file in "${env_files[@]}"
do
	eval "file=$file" # expand the path correctly

	if [[ ! -f $file ]]
	then
		touch $file
	fi

	if grep -q "source ~/.drm/function.sh" $file
	then
		continue
	fi

	echo "Adding env entries to: $file"
	cat - >> $file <<-EOF
		# Generated by: DRM
		source ~/.drm/function.sh
	EOF

	if (( $? ))
	then
		echo "Error updating file [$file]"
		exit 1
	fi
done

docker rmi -f drm_mac